name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        # uses: SonarSource/sonarcloud-github-action@v1.9.0
        uses: SonarSource/sonarcloud-github-action@v1

        with:
          projectKey: Tjitouua_gondwana-assignment
          organization: tjitouua
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
